Fix #23 - Replace only some java.lang classes and support subtypes
rizinorg/rz-libdemangle pull request #26
Opened 2022-08-24 20:56 UTC by wargio

Replaces only some `java.lang` classes (like Void, String, etc..) and adds support for subtypes (including templates)

Fix #23 

@haeter525 Please verify this PR.

2022-08-25 16:19 UTC, XVilka requested changes
LGTM.

2022-08-25 16:19 UTC, XVilka commented on src/java.c
> +static java_replace_t java_replace_table[] = {
Please add a comment where from and what for this table is

2022-08-26 09:59 UTC, haeter525 commented
> @haeter525 Please verify this PR.

Confirm #23 is fixed. Thanks :D

2022-08-26 13:35 UTC, XVilka approved these changes

2022-08-26 13:51 UTC, merged