Implement demangler for Rust
rizinorg/rz-libdemangle pull request #32
Opened 2023-02-27 05:12 UTC by DMaroo

The demangler still wouldn't work for the executable specified in #30, but that is because of rizinorg/rizin#3404. The demangler is correct and complete, as evidenced in the tests.

2023-02-27 05:18 UTC, XVilka requested changes
Please add more tests from https://doc.servo.org/src/rustc_demangle/legacy.rs.html#242

2023-02-28 04:02 UTC, XVilka approved these changes

2023-02-28 14:08 UTC, wargio commented on src/rust.c
> +uint32_t utf_to_bytes(uint32_t utf) {
static

2023-02-28 14:08 UTC, wargio commented on src/rust.c
> +uint32_t rebase_value(uint8_t char_code, uint8_t base) {
static

2023-02-28 14:08 UTC, wargio commented on src/rust.c
> +uint32_t get_integer(const char **str, uint8_t base) {
static

2023-02-28 14:08 UTC, wargio commented on src/rust.c
> +DemString *replace_utf(const char *utf_str) {
static

2023-02-28 15:40 UTC, wargio requested changes
If i remember correctly the rust code in the first releases was using the c++ demangler (that is why we have that).
I'm not sure if i can find the info again, but could be an edge case.

2023-02-28 15:51 UTC, wargio commented
Please update the header also with only your name since you have rewritten it completely

2023-03-01 02:09 UTC, DMaroo commented
>  If i remember correctly the rust code in the first releases was using the c++ demangler (that is why we have that).
I'm not sure if i can find the info again, but could be an edge case.

It isn't really needed. There can be calls to C/C++ functions (dynamically linked) in a Rust binary, but we should ideally first run the Rust demangler and then the C++ demangler on the symbols. This way the licensing is much less painful, since the Rust demangler can stay LGPL, since it does not use the C++ demangler.

2023-03-01 02:29 UTC, XVilka approved these changes

2023-03-01 02:50 UTC, merged

2023-03-01 02:50 UTC, XVilka commented
@DMaroo please send a PR to update it in Rizin

2023-03-24 13:26 UTC, DMaroo commented
Corresponding Rizin PR: rizinorg/rizin#3430